server:
  port: 80
spring:
  application:
    name: feign-order-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #单机版


#设置feign 客户端超时时间(openfeign 默认支持ribbon)
#ribbon:
##  #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeOut: 5000
##  #建立连接后从服务器读取到可用资源的时间
#  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    #feign 日志以什么级别监控哪个接口
    com.ceking.springcloud.service.PaymentFeignService: debug